# tracker/report.py

from pathlib import Path

def build_markdown_report(records):
    """
    Membuat teks laporan lengkap dalam format Markdown dari data rekap.
    
    Args:
        records (list): Daftar dictionary hasil dari RekapKelas.rekap().
        
    Returns:
        str: Teks lengkap laporan dalam format Markdown.
    """
    lines = [
        "# Rekap Kinerja Mahasiswa",
        "",
        "| NIM | Nama | Hadir (%) | Nilai Akhir | Predikat |",
        "|---|---|---:|---:|:---|",
    ]

    for r in records:
        
        lines.append(
            "| {nim} | {nama} | {hadir:.2f} | {akhir:.2f} | {pred} |".format(
                nim=r["nim"],
                nama=r["nama"],
                hadir=r["hadir"],
                akhir=r["akhir"],
                pred=r["predikat"],
            )
        )
    
    lines.append("")
    lines.append("Generated by student_performance_tracker.")
    return "\n".join(lines)

def save_text(path, content):
    """
    Menyimpan konten teks (content) ke sebuah file (path).
    
    Args:
        path (str): Lokasi file tujuan, mis. "out/report.md".
        content (str): Teks yang akan disimpan.
    """
   
    output_dir = Path(path).parent
    output_dir.mkdir(parents=True, exist_ok=True)
    
 
    try:
        Path(path).write_text(content, encoding="utf-8")
    except Exception as e:
        raise IOError(f"Gagal menyimpan file ke {path}: {e}")

def letter_grade(score):
    """
    Mengubah skor angka (0-100) menjadi predikat huruf (A-E).
    
    Args:
        score (float): Nilai akhir.
        
    Returns:
        str: Predikat huruf.
    """
    if score >= 85:
        return "A"
    if score >= 75:
        return "B"
    if score >= 65:
        return "C"
    if score >= 50:
        return "D"
    return "E"

def build_html_report(records):
    """
    Membuat teks laporan lengkap dalam format HTML
    dengan warna baris berdasarkan predikat [cite: 971].
    
    Args:
        records (list): Daftar dictionary hasil dari RekapKelas.rekap().
        
    Returns:
        str: Teks lengkap laporan dalam format HTML.
    """
    # 1. Template awal HTML
    html = """
    <html>
    <head>
        <title>Rekap Kinerja Mahasiswa</title>
        <style>
            body { font-family: sans-serif; margin: 2em; }
            table { border-collapse: collapse; width: 80%; margin: auto; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            th { background-color: #f2f2f2; }
            h1 { text-align: center; font-size: 1.8em; }
            
            /* Warna berdasarkan predikat */
            .pred-A { background-color: #e6ffed; } /* Hijau muda */
            .pred-B { background-color: #e6f7ff; } /* Biru muda */
            .pred-C { background-color: #fffbeb; } /* Kuning muda */
            .pred-D { background-color: #fff0e6; } /* Oranye muda */
            .pred-E { background-color: #ffe6e6; } /* Merah muda */
            
            .footer { font-size: 0.8em; color: #777; margin-top: 1em; text-align: center; }
        </style>
    </head>
    <body>
    
    <h1>Rekap Kinerja Mahasiswa</h1>
    
    <table>
        <thead>
            <tr>
                <th>NIM</th>
                <th>Nama</th>
                <th>Hadir (%)</th>
                <th>Nilai Akhir</th>
                <th>Predikat</th>
            </tr>
        </thead>
        <tbody>
    """
    
    # 2. Isi tabel dengan data
    for r in records:
        predikat = r['predikat']
        html += f"<tr class='pred-{predikat}'>\n"
        html += f"    <td>{r['nim']}</td>\n"
        html += f"    <td>{r['nama']}</td>\n"
        html += f"    <td style='text-align: right;'>{r['hadir']:.2f}</td>\n"
        html += f"    <td style='text-align: right;'>{r['akhir']:.2f}</td>\n"
        html += f"    <td style='text-align: center;'>{predikat}</td>\n"
        html += "</tr>\n"
        
    # 3. Tutup template HTML
    html += """
        </tbody>
    </table>
    
    <p class='footer'>Generated by student_performance_tracker.</p>
    
    </body>
    </html>
    """
    return html
